from __future__ import annotations

from pathlib import Path


OUTPUT_ROOT = Path("etfs/output")
METHODOLOGY_PDF_DIR = OUTPUT_ROOT / "methodologies"
REFRESH_DIR = Path("etfs/refresh")
REFRESH_TEMPLATE_XLSX = REFRESH_DIR / "pdf.xlsx"
REFRESH_TICKER_XLSX = REFRESH_DIR / "ticker.xlsx"
REFRESH_WORK_DIR = REFRESH_DIR / "work"
REFRESH_MANIFEST_JSON = REFRESH_WORK_DIR / "refresh_manifest.json"

CATALOG_OUTPUT_DIR = OUTPUT_ROOT / "catalog"
UNIVERSE_OUTPUT_DIR = CATALOG_OUTPUT_DIR
CLASSIFICATION_OUTPUT_DIR = CATALOG_OUTPUT_DIR
SOURCES_OUTPUT_DIR = CATALOG_OUTPUT_DIR

METHODOLOGY_OUTPUT_DIR = OUTPUT_ROOT / "methodology"
FNGUIDE_OUTPUT_DIR = METHODOLOGY_OUTPUT_DIR / "fnguide"
KRX_OUTPUT_DIR = METHODOLOGY_OUTPUT_DIR / "krx"
SPGLOBAL_OUTPUT_DIR = METHODOLOGY_OUTPUT_DIR / "spglobal"
NASDAQ_OUTPUT_DIR = METHODOLOGY_OUTPUT_DIR / "nasdaq"
MSCI_OUTPUT_DIR = METHODOLOGY_OUTPUT_DIR / "msci"

FNGUIDE_EXTRACTION_OUTPUT_DIR = FNGUIDE_OUTPUT_DIR
FNGUIDE_ENGINE_OUTPUT_DIR = FNGUIDE_OUTPUT_DIR

ALL_ETFS_CSV = UNIVERSE_OUTPUT_DIR / "all.csv"
SECTOR_CSV = UNIVERSE_OUTPUT_DIR / "sector.csv"
UNIVERSE_JSON = UNIVERSE_OUTPUT_DIR / "universe.json"

FAMILIES_JSON = CLASSIFICATION_OUTPUT_DIR / "families.json"
SOURCES_JSON = SOURCES_OUTPUT_DIR / "sources.json"

FNGUIDE_PDFS_JSON = FNGUIDE_OUTPUT_DIR / "pdfs.json"
FNGUIDE_RULES_JSON = FNGUIDE_OUTPUT_DIR / "rules.json"
FNGUIDE_REQUIREMENTS_JSON = FNGUIDE_OUTPUT_DIR / "requirements.json"
FNGUIDE_EXTRACTIONS_JSON = FNGUIDE_EXTRACTION_OUTPUT_DIR / "methodology_extractions.json"
FNGUIDE_DRAFT_SPECS_JSON = FNGUIDE_EXTRACTION_OUTPUT_DIR / "draft_specs.json"
FNGUIDE_SPEC_OVERRIDES_JSON = FNGUIDE_EXTRACTION_OUTPUT_DIR / "spec_overrides.json"
FNGUIDE_METHODOLOGY_SPECS_JSON = FNGUIDE_EXTRACTION_OUTPUT_DIR / "methodology_specs.json"
FNGUIDE_METHODOLOGY_AUDIT_JSON = FNGUIDE_EXTRACTION_OUTPUT_DIR / "methodology_audit.json"
FNGUIDE_METHODOLOGY_REVIEW_QUEUE_JSON = FNGUIDE_EXTRACTION_OUTPUT_DIR / "methodology_review_queue.json"
FNGUIDE_ENGINE_INPUTS_JSON = FNGUIDE_ENGINE_OUTPUT_DIR / "engine_inputs.json"
FNGUIDE_ENGINE_INPUT_TEMPLATE_JSON = FNGUIDE_ENGINE_OUTPUT_DIR / "engine_inputs.template.json"
FNGUIDE_ENGINE_INPUT_REQUIREMENTS_JSON = FNGUIDE_ENGINE_OUTPUT_DIR / "engine_input_requirements.json"
FNGUIDE_ENGINE_SUPPORT_MATRIX_JSON = FNGUIDE_ENGINE_OUTPUT_DIR / "engine_support_matrix.json"
FNGUIDE_ENGINE_PROMOTION_CANDIDATES_JSON = FNGUIDE_ENGINE_OUTPUT_DIR / "engine_promotion_candidates.json"
FNGUIDE_METHODOLOGY_REPLICATION_REPORT_JSON = FNGUIDE_OUTPUT_DIR / "methodology_replication_report.json"
FNGUIDE_TARGET_WEIGHTS_JSON = FNGUIDE_ENGINE_OUTPUT_DIR / "target_weights.json"
FNGUIDE_DATA_INVENTORY_JSON = FNGUIDE_OUTPUT_DIR / "data_inventory.json"
FNGUIDE_DATA_INVENTORY_MD = FNGUIDE_OUTPUT_DIR / "data_inventory.md"
FNGUIDE_ETF_METHODOLOGY_SUMMARY_JSON = FNGUIDE_OUTPUT_DIR / "etf_methodology_summary.json"
FNGUIDE_ETF_METHODOLOGY_SUMMARY_CSV = FNGUIDE_OUTPUT_DIR / "etf_methodology_summary.csv"
FNGUIDE_ETF_METHODOLOGY_SUMMARY_MD = FNGUIDE_OUTPUT_DIR / "etf_methodology_summary.md"

VALIDATION_OUTPUT_DIR = OUTPUT_ROOT / "validation"
VALIDATION_FIXTURES_JSON = VALIDATION_OUTPUT_DIR / "validation_fixtures.json"
VALIDATION_RESULTS_JSON = VALIDATION_OUTPUT_DIR / "validation_results.json"
CAP_CANDIDATES_JSON = VALIDATION_OUTPUT_DIR / "cap_candidates.json"
CAP_CANDIDATES_MD = VALIDATION_OUTPUT_DIR / "cap_candidates.md"
REFRESHED_HOLDINGS_FILES_DIR = OUTPUT_ROOT / "files"
TARGET_WEIGHT_VALIDATION_JSON = VALIDATION_OUTPUT_DIR / "target_weight_validation.json"
