from __future__ import annotations

from pathlib import Path


OUTPUT_ROOT = Path("etfs/output")

UNIVERSE_OUTPUT_DIR = OUTPUT_ROOT / "universe"
CLASSIFICATION_OUTPUT_DIR = OUTPUT_ROOT / "classification"
SOURCES_OUTPUT_DIR = OUTPUT_ROOT / "sources"

PROVIDERS_OUTPUT_DIR = OUTPUT_ROOT / "providers"
FNGUIDE_OUTPUT_DIR = PROVIDERS_OUTPUT_DIR / "fnguide"
KRX_OUTPUT_DIR = PROVIDERS_OUTPUT_DIR / "krx"
SPGLOBAL_OUTPUT_DIR = PROVIDERS_OUTPUT_DIR / "spglobal"
NASDAQ_OUTPUT_DIR = PROVIDERS_OUTPUT_DIR / "nasdaq"
MSCI_OUTPUT_DIR = PROVIDERS_OUTPUT_DIR / "msci"

EXTRACTIONS_OUTPUT_DIR = OUTPUT_ROOT / "extractions"
FNGUIDE_EXTRACTION_OUTPUT_DIR = EXTRACTIONS_OUTPUT_DIR / "fnguide"
ENGINE_OUTPUT_DIR = OUTPUT_ROOT / "engine"
FNGUIDE_ENGINE_OUTPUT_DIR = ENGINE_OUTPUT_DIR / "fnguide"
REPLICATION_OUTPUT_DIR = OUTPUT_ROOT / "replication"
FNGUIDE_REPLICATION_OUTPUT_DIR = REPLICATION_OUTPUT_DIR / "fnguide"

ALL_ETFS_CSV = UNIVERSE_OUTPUT_DIR / "all.csv"
SECTOR_CSV = UNIVERSE_OUTPUT_DIR / "sector.csv"
UNIVERSE_JSON = UNIVERSE_OUTPUT_DIR / "universe.json"

FAMILIES_JSON = CLASSIFICATION_OUTPUT_DIR / "families.json"
SOURCES_JSON = SOURCES_OUTPUT_DIR / "sources.json"

FNGUIDE_PDFS_JSON = FNGUIDE_OUTPUT_DIR / "pdfs.json"
FNGUIDE_RULES_JSON = FNGUIDE_OUTPUT_DIR / "rules.json"
FNGUIDE_REQUIREMENTS_JSON = FNGUIDE_OUTPUT_DIR / "requirements.json"
FNGUIDE_EXTRACTIONS_JSON = FNGUIDE_EXTRACTION_OUTPUT_DIR / "methodology_extractions.json"
FNGUIDE_DRAFT_SPECS_JSON = FNGUIDE_EXTRACTION_OUTPUT_DIR / "draft_specs.json"
FNGUIDE_SPEC_OVERRIDES_JSON = FNGUIDE_EXTRACTION_OUTPUT_DIR / "spec_overrides.json"
FNGUIDE_METHODOLOGY_SPECS_JSON = FNGUIDE_EXTRACTION_OUTPUT_DIR / "methodology_specs.json"
FNGUIDE_METHODOLOGY_AUDIT_JSON = FNGUIDE_EXTRACTION_OUTPUT_DIR / "methodology_audit.json"
FNGUIDE_METHODOLOGY_REVIEW_QUEUE_JSON = FNGUIDE_EXTRACTION_OUTPUT_DIR / "methodology_review_queue.json"
FNGUIDE_ENGINE_INPUTS_JSON = FNGUIDE_ENGINE_OUTPUT_DIR / "engine_inputs.json"
FNGUIDE_ENGINE_INPUT_TEMPLATE_JSON = FNGUIDE_ENGINE_OUTPUT_DIR / "engine_inputs.template.json"
FNGUIDE_ENGINE_INPUT_REQUIREMENTS_JSON = FNGUIDE_ENGINE_OUTPUT_DIR / "engine_input_requirements.json"
FNGUIDE_ENGINE_SUPPORT_MATRIX_JSON = FNGUIDE_ENGINE_OUTPUT_DIR / "engine_support_matrix.json"
FNGUIDE_ENGINE_PROMOTION_CANDIDATES_JSON = FNGUIDE_ENGINE_OUTPUT_DIR / "engine_promotion_candidates.json"
FNGUIDE_METHODOLOGY_REPLICATION_REPORT_JSON = FNGUIDE_ENGINE_OUTPUT_DIR / "methodology_replication_report.json"
FNGUIDE_TARGET_WEIGHTS_JSON = FNGUIDE_ENGINE_OUTPUT_DIR / "target_weights.json"
FNGUIDE_KSS_REQUIREMENTS_JSON = FNGUIDE_REPLICATION_OUTPUT_DIR / "kss_data_requirements.json"
FNGUIDE_KSS_SELECTED_BUCKETS_JSON = FNGUIDE_REPLICATION_OUTPUT_DIR / "kss_selected_buckets.json"
FNGUIDE_KSS_TARGET_WEIGHTS_JSON = FNGUIDE_REPLICATION_OUTPUT_DIR / "kss_target_weights.json"
FNGUIDE_KSS_VALIDATION_JSON = FNGUIDE_REPLICATION_OUTPUT_DIR / "kss_replication_validation.json"
FNGUIDE_KSS_VALIDATION_MD = FNGUIDE_REPLICATION_OUTPUT_DIR / "kss_replication_validation.md"

VALIDATION_OUTPUT_DIR = OUTPUT_ROOT / "validation"
VALIDATION_FIXTURES_JSON = VALIDATION_OUTPUT_DIR / "validation_fixtures.json"
VALIDATION_RESULTS_JSON = VALIDATION_OUTPUT_DIR / "validation_results.json"
TARGET_WEIGHT_VALIDATION_JSON = VALIDATION_OUTPUT_DIR / "target_weight_validation.json"
