from enum import Enum, unique


@unique
class DatasetGroup(str, Enum):
    PRICE = "price"
    FUNDAMENTAL = "fundamental"
    ESTIMATE = "estimate"
    FLOW = "flow"
    FLAG = "flag"
    META = "meta"
    BENCHMARK = "benchmark"


@unique
class DatasetId(str, Enum):
    QW_ADJ_C = "qw_adj_c"
    QW_ADJ_H = "qw_adj_h"
    QW_ADJ_L = "qw_adj_l"
    QW_ADJ_O = "qw_adj_o"
    QW_ASSET_LFQ0 = "qw_asset_lfq0"
    QW_BM = "qw_BM"
    QW_C = "qw_c"
    QW_EPS_NFQ1 = "qw_eps_nfq1"
    QW_EPS_NFQ2 = "qw_eps_nfq2"
    QW_EPS_NFY1 = "qw_eps_nfy1"
    QW_EQUITY_LFQ0 = "qw_equity_lfq0"
    QW_FOREIGN = "qw_foreign"
    QW_FOREIGN_RATIO = "qw_foreign_ratio"
    QW_GP_LFQ0 = "qw_gp_lfq0"
    QW_INSTITUTION = "qw_institution"
    QW_K200_YN = "qw_k200_yn"
    QW_KSDQ150_YN = "qw_ksdq150_yn"
    QW_KSDQ_ADJ_C = "qw_ksdq_adj_c"
    QW_KSDQ_ADJ_H = "qw_ksdq_adj_h"
    QW_KSDQ_ADJ_L = "qw_ksdq_adj_l"
    QW_KSDQ_ADJ_O = "qw_ksdq_adj_o"
    QW_KSDQ_MKTCAP = "qw_ksdq_mktcap"
    QW_KSDQ_MKTCAP_FLT = "qw_ksdq_mktcap_flt"
    QW_KSDQ_V = "qw_ksdq_v"
    QW_KSDQ_WICS_SEC_BIG = "qw_ksdq_wics_sec_big"
    QW_LIABILITY_LFQ0 = "qw_liability_lfq0"
    QW_MKTCAP = "qw_mktcap"
    QW_MKTCAP_FLT = "qw_mktcap_flt"
    QW_MKT_TYP = "qw_mkt_typ"
    QW_NI_LFQ0 = "qw_ni_lfq0"
    QW_OCF_LFQ0 = "qw_ocf_lfq0"
    QW_OP_LFQ0 = "qw_op_lfq0"
    QW_OP_NFQ1 = "qw_op_nfq1"
    QW_OP_NFQ2 = "qw_op_nfq2"
    QW_OP_NFY1 = "qw_op_nfy1"
    QW_RETAIL = "qw_retail"
    QW_SHA_OUT = "qw_sha_out"
    QW_TRS_BAN = "qw_trs_ban"
    QW_V = "qw_v"
    QW_WICS_SEC_BIG = "qw_wics_sec_big"
